In [1]:
import os, sys
import pandas as pd
import pandas_ta as ta
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), 'data')))
from price_fetcher import fetch_adjusted_prices

In [10]:
df = fetch_adjusted_prices("MSFT", "2023-01-01", "2024-01-10")
print(df)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2023-01-03  234.423569  240.460771  232.290481  237.848239  25740000
2023-01-04  224.169144  227.857992  221.096726  227.280694  50623400
2023-01-05  217.525299  222.652526  216.987134  222.310053  39585600
2023-01-06  220.088898  220.901036  214.629007  218.200444  43613600
2023-01-09  222.231735  226.263071  221.537025  221.576157  27369800
...                ...         ...         ...         ...       ...
2024-01-03  365.839020  368.464851  363.775873  364.269450  23083500
2024-01-04  363.213196  368.306911  362.453099  365.908135  20901500
2024-01-05  363.025635  367.280263  361.791693  364.229963  21004600
2024-01-08  369.876465  370.379923  364.269441  364.555694  23134000
2024-01-09  370.962341  371.159754  366.421430  367.230903  20830000

[256 rows x 5 columns]
Price             Open        High         Low       Close    Volume
Date
2023-01-03  237.848239  240.460771  232.290481  234.423569  25740000
2023-01-04  227.280694  227.857992  221.096726  224.169144  50623400
2023-01-05  222.310053  222.652526  216.987134  217.525299  39585600
2023-01-06  218.200444  220.901036  214.629007  220.088898  43613600
2023-01-09  221.576157  226.263071  221.537025  222.231735  27369800
...                ...         ...         ...         ...       ...
2024-01-03  364.269450  368.464851  363.775873  365.839020  23083500
2024-01-04  365.908135  368.306911  362.453099  363.213196  20901500
2024-01-05  364.229963  367.280263  361.791693  363.025635  21004600
2024-01-08  364.555694  370.379923  364.269441  369.876465  23134000
2024-01-09  367.230903  371.159754  366.421430  370.962341  20830000

[256 rows x 5 columns]

In [3]:
df.ta.sma(length=[10, 50], append=True)
print(df)

Price             Open        High         Low       Close    Volume  \
Date
2023-01-03  237.848239  240.460771  232.290481  234.423569  25740000
2023-01-04  227.280694  227.857992  221.096726  224.169144  50623400
2023-01-05  222.310053  222.652526  216.987134  217.525299  39585600
2023-01-06  218.200444  220.901036  214.629007  220.088898  43613600
2023-01-09  221.576157  226.263071  221.537025  222.231735  27369800
...                ...         ...         ...         ...       ...
2024-01-03  364.269450  368.464851  363.775873  365.839020  23083500
2024-01-04  365.908135  368.306911  362.453099  363.213196  20901500
2024-01-05  364.229963  367.280263  361.791693  363.025635  21004600
2024-01-08  364.555694  370.379923  364.269441  369.876465  23134000
2024-01-09  367.230903  371.159754  366.421430  370.962341  20830000

Price           SMA_10
Date
2023-01-03         NaN
2023-01-04         NaN
2023-01-05         NaN
2023-01-06         NaN
2023-01-09         NaN
...                ...
2024-01-03  368.555667
2024-01-04  368.030502
2024-01-05  367.747192
2024-01-08  367.860715
2024-01-09  367.980161

[256 rows x 6 columns]

In [9]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), 'features')))
from feature_store import compute_indicator

In [11]:
out = compute_indicator(df, "sma", {"length": 10})
print(out)

                SMA_10
Date
2023-01-03         NaN
2023-01-04         NaN
2023-01-05         NaN
2023-01-06         NaN
2023-01-09         NaN
...                ...
2024-01-03  368.555667
2024-01-04  368.030502
2024-01-05  367.747192
2024-01-08  367.860715
2024-01-09  367.980161

[256 rows x 1 columns]